require('dotenv').config();
const fs = require('fs');
const path = require('path');
const nodemailer = require('nodemailer');

function today() {
  return new Date().toISOString().split('T')[0];
}

function rankEmoji(rank) {
  if (!rank) return '❌';
  if (rank <= 3) return '🥇';
  if (rank <= 10) return '🟢';
  if (rank <= 20) return '🟡';
  return '🔴';
}

function changeStr(change) {
  if (change === null || change === undefined) return '(new)';
  if (change > 0) return `▲${change}`;
  if (change < 0) return `▼${Math.abs(change)}`;
  return '—';
}

function buildReport(results) {
  const date = today();
  let text = `SEO RANK REPORT — ${date}\n${'='.repeat(50)}\n\n`;
  let html = `<h2>SEO Rank Report — ${date}</h2>`;

  for (const [site, data] of Object.entries(results)) {
    text += `${site.toUpperCase()}\n${'-'.repeat(40)}\n`;
    html += `<h3>${site}</h3><table border="1" cellpadding="6" style="border-collapse:collapse;font-family:monospace">`;
    html += `<tr><th>Keyword</th><th>Rank</th><th>Change</th><th>Top Competitor</th></tr>`;

    for (const [keyword, data_] of Object.entries(data.keywords)) {
      const rank = data_.rank ? `#${data_.rank}` : 'Not found';
      const change = changeStr(data_.change);
      const emoji = rankEmoji(data_.rank);

      // Find top competitor for this keyword (lowest rank number, excluding client site)
      const topComp = Object.entries(data_.competitors || {})
        .sort((a, b) => a[1] - b[1])[0];
      const compStr = topComp ? `${topComp[0]} (#${topComp[1]})` : '—';

      text += `  ${emoji} ${keyword.padEnd(45)} ${rank.padEnd(10)} ${change}\n`;
      text += `     Top competitor: ${compStr}\n`;
      html += `<tr><td>${keyword}</td><td>${emoji} ${rank}</td><td>${change}</td><td>${compStr}</td></tr>`;
    }

    text += '\n';
    html += `</table><br>`;
  }

  html += `<p style="color:#999;font-size:12px">Generated by seo-monitor · ${date}</p>`;
  return { text, html };
}

async function sendEmail(subject, text, html) {
  if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
    console.log('No SMTP config — printing report to console:\n');
    console.log(text);
    return;
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS }
  });

  await transporter.sendMail({
    from: process.env.SMTP_USER,
    to: process.env.REPORT_EMAIL || process.env.SMTP_USER,
    subject,
    text,
    html
  });

  console.log(`Report emailed to ${process.env.REPORT_EMAIL || process.env.SMTP_USER}`);
}

async function sendSlack(text) {
  if (!process.env.SLACK_WEBHOOK_URL) return;

  const payload = {
    text: `*SEO Rank Report — ${today()}*`,
    blocks: [
      { type: 'header', text: { type: 'plain_text', text: `SEO Ranks — ${today()}` } },
      { type: 'section', text: { type: 'mrkdwn', text: '```' + text + '```' } }
    ]
  };

  const res = await fetch(process.env.SLACK_WEBHOOK_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload)
  });

  if (res.ok) console.log('Slack report sent');
}

async function run() {
  const date = today();
  const snapshotFile = path.join(__dirname, `snapshot-${date}.json`);

  if (!fs.existsSync(snapshotFile)) {
    console.error(`No snapshot found for ${date}. Run tracker.js first.`);
    process.exit(1);
  }

  const results = JSON.parse(fs.readFileSync(snapshotFile, 'utf8'));
  const { text, html } = buildReport(results);

  await sendEmail(`SEO Ranks — ${date}`, text, html);
  await sendSlack(text);
}

run().catch(console.error);
