require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { Resend } = require('resend');

function today() {
  return new Date().toISOString().split('T')[0];
}

function rankEmoji(rank) {
  if (!rank) return '❌';
  if (rank <= 3) return '🥇';
  if (rank <= 10) return '🟢';
  if (rank <= 20) return '🟡';
  return '🔴';
}

function changeStr(change) {
  if (change === null || change === undefined) return '(new)';
  if (change > 0) return `▲${change}`;
  if (change < 0) return `▼${Math.abs(change)}`;
  return '—';
}

function buildReport(results) {
  const date = today();
  let text = `SEO RANK REPORT — ${date}\n${'='.repeat(50)}\n\n`;
  let html = `
    <div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;color:#222">
    <h2 style="border-bottom:2px solid #D4A017;padding-bottom:8px">SEO Rank Report — ${date}</h2>
  `;

  for (const [site, data] of Object.entries(results)) {
    text += `${site.toUpperCase()}\n${'-'.repeat(40)}\n`;
    html += `
      <h3 style="margin-top:28px;color:#333">${site}</h3>
      <table style="width:100%;border-collapse:collapse;font-size:14px">
        <thead>
          <tr style="background:#f5f5f5">
            <th style="text-align:left;padding:8px;border:1px solid #ddd">Keyword</th>
            <th style="text-align:center;padding:8px;border:1px solid #ddd">Rank</th>
            <th style="text-align:center;padding:8px;border:1px solid #ddd">Change</th>
            <th style="text-align:left;padding:8px;border:1px solid #ddd">Top Competitor</th>
          </tr>
        </thead>
        <tbody>
    `;

    for (const [keyword, d] of Object.entries(data.keywords)) {
      const rank = d.rank ? `#${d.rank}` : 'Not found';
      const change = changeStr(d.change);
      const emoji = rankEmoji(d.rank);
      const topComp = Object.entries(d.competitors || {}).sort((a, b) => a[1] - b[1])[0];
      const compStr = topComp ? `${topComp[0]} (#${topComp[1]})` : '—';
      const rowBg = d.change > 0 ? '#f0fff4' : d.change < 0 ? '#fff5f5' : '#fff';

      text += `  ${emoji} ${keyword.padEnd(45)} ${rank.padEnd(10)} ${change}\n`;
      text += `     Top competitor: ${compStr}\n`;
      html += `
        <tr style="background:${rowBg}">
          <td style="padding:8px;border:1px solid #ddd">${keyword}</td>
          <td style="text-align:center;padding:8px;border:1px solid #ddd">${emoji} ${rank}</td>
          <td style="text-align:center;padding:8px;border:1px solid #ddd">${change}</td>
          <td style="padding:8px;border:1px solid #ddd;font-size:12px;color:#666">${compStr}</td>
        </tr>
      `;
    }

    text += '\n';
    html += `</tbody></table>`;
  }

  html += `
    <p style="margin-top:32px;font-size:12px;color:#999;border-top:1px solid #eee;padding-top:12px">
      Generated by seo-monitor · ${date} · <a href="https://github.com/iambenfinnie/seo-monitor">github.com/iambenfinnie/seo-monitor</a>
    </p>
    </div>
  `;

  return { text, html };
}

async function sendEmail(date, text, html) {
  if (!process.env.RESEND_API_KEY) {
    console.log('No RESEND_API_KEY — printing report:\n');
    console.log(text);
    return;
  }

  const resend = new Resend(process.env.RESEND_API_KEY);
  const { error } = await resend.emails.send({
    from: 'SEO Monitor <Ben@sevengensystems.com>',
    to: ['Ben@sevengensystems.com'],
    subject: `SEO Ranks — ${date}`,
    html,
    text
  });

  if (error) {
    console.error('Email failed:', error);
  } else {
    console.log('Report emailed to Ben@sevengensystems.com');
  }
}

async function run() {
  const date = today();
  const snapshotFile = path.join(__dirname, `snapshot-${date}.json`);

  if (!fs.existsSync(snapshotFile)) {
    console.error(`No snapshot for ${date}. Run tracker.js first.`);
    process.exit(1);
  }

  const results = JSON.parse(fs.readFileSync(snapshotFile, 'utf8'));
  const { text, html } = buildReport(results);
  await sendEmail(date, text, html);
}

run().catch(console.error);
